'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ButikDaurUlang.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_11_Agreement_report_form_layout_paper_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_11_Agreement_report_form_layout_paper_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_16_agreement_paperDocument_note_report_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_16_agreement_paperDocument_note_report_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_25_earth_recycle_green_4079663() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_25-earth-recycle-green_4079663", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_31_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_31_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_aiga_cashier_134157__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_aiga_cashier_134157 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_aiga_cashier_134157__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_aiga_cashier_134157 (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_aiga_cashier_48px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_aiga_cashier_48px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_aiga_cashier_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_aiga_cashier_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_cancel_16px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_cancel_16px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_cancel_20px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_cancel_20px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_Dollar_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_Dollar_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_Dollar_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_Dollar_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_f015_20px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_f015_20px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_f015_20px1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_f015_20px1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_home_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_home_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_home_24px1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_home_24px1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_home_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_home_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_home_48px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_home_48px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_home_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_home_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_ic_attach_money_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_ic_attach_money_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_lock_24_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_lock-24_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_maximize_16px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_maximize_16px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_maximize_16px__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_maximize_16px (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_minus_16px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_minus_16px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_money_bag_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_money_bag_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_money_bag_24px1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_money_bag_24px1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_money_bag_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_money_bag_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_money_coin_price_buy_cost_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_money-coin-price-buy-cost_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_people_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_people_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_people_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_people_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_recycle_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_recycle_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_recycle_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_recycle_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_seo_report_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_seo-report_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_sign_out_20px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_sign-out_20px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_sign_out_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_sign-out_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_user_20px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_user_20px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_user_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_user_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_user_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_user_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_write_126582() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_write_126582", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconfinder_write_20px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconfinder_write_20px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo_Butik_Daur_Ulang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo Butik Daur Ulang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Max() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Max", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhatsApp_Image_2020_01_10_at_12_00_41_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhatsApp Image 2020-01-10 at 12.00.41 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
